### ISSUE TITLE
bitping cli stuck after auto update

### ISSUE THREAD

**Issue by syahpian** [BitpingApp/Bitping-Node#6]
Device: RPI4
OS: Ubuntu 22.04
Issue: cli stuck after auto update, need to manually restart cli using systemd to make it working again

![image](https://github.com/BitpingApp/Bitping-Node/assets/12189144/0ceea2cc-735e-4bb7-96b4-b7206d613f62)

![image](https://github.com/BitpingApp/Bitping-Node/assets/12189144/3c511db6-31c7-4844-9741-85bafa142898)

**Comment by Firaenix** [comment]
I just ran into this as well, I will investigate. Thanks for the ticket!

**Comment by Firaenix** [comment]
After some thought I think what I need to do is have a way for Bitpingd to know if it was run from Systemd or Launchd. I can probably do this by adding an environment variable to the systemd/launchd unit like SERVICE_MANAGER=true and then I can get Bitpingd to update the binary, fix its own permissions on linux to re-enable ICMP packet support and then call systemctl restart bitping-bitpingd to have it run the new binary.

To do this I'll probably have to reimplement how we do service management from scratch and instead of using a generic library, I'll have to use a specific library per operating system.
